### ISSUE TITLE
MathJax fails with newest version of Discourse? v1.9.0.beta4 +145

### ISSUE THREAD

**Issue by norandom** [kasperpeulen/discourse-mathjax#43]
Hi,

I ran into an error:

```
Uncaught TypeError: Cannot read property 'inlineBetween' of undefined
    at plugin-third-party-288137a51d11831a19341218e92bfc5dbdeb774ced17877d7d3ff2353bec8161.js:1
    at plugin-third-party-288137a51d11831a19341218e92bfc5dbdeb774ced17877d7d3ff2353bec8161.js:1
```

MathJax does not work with Discourse, probably due to this file:
https://github.com/kasperpeulen/discourse-mathjax/blob/6b7ca800de53a424f52cb2ea36d8ee9ee0c0470f/assets/javascripts/tex_dialect.js 

Discourse Version: v1.9.0.beta4 +145 
MathJax repo: (from app.yml)

`git clone https://github.com/kasperpeulen/discourse-mathjax`

Not sure why... for now.

**Comment by norandom** [comment]
https://github.com/rux-pizza/discourse-mathjax  - fixed here.

**Comment by xiasummer** [comment]
you mean https://github.com/rux-pizza/discourse-mathjax can fix this problem?

But I tried and still not working. Do you have more solutions?


------

20170723, I found it working. Don't know why, just install https://github.com/rux-pizza/discourse-mathjax is OK.

**Comment by qnxor** [comment]
I'm having the same problem. How exactly did you guys make it work?

I added the `git clone https://github.com/rux-pizza/discourse-mathjax.git` line in `app.yml` then did a `./launcher app rebuild` but my posts are still bare. I tried a `rake posts:rebake` to no avail.

Before this I tried the newer `Math` plugin which works with v1.9 but doesn't support many features. I'm trying to go back to the mathjax plugin but have so far been unsuccessful.

**Comment by qnxor** [comment]
Got it ... I had to disable the newer `math` plugin by commenting it out in `app.yml` then did a `./launcher app rebuild` followed by `./launcher enter app` and `rake posts:rebake`. Leaving this here in case others have the same problem.

The original plugin repo loads a file meant for adding compatibility with older Discourse versions, and this file calls functions which are no longer available in v1.9, hence it fails. This is good to know for the future as it allows a quick manual fix for newer Discourse versions ... hopefully.
